# Generated by Django 5.2.4 on 2025-08-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
