# Generated by Django 5.2.4 on 2025-08-03 00:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_qr', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier encoded in the QR code', unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='devices/images/')),
                ('model', models.CharField(max_length=50)),
                ('date_achat', models.DateField(verbose_name='Date Ahat')),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='available', max_length=20)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='Amine', max_length=100, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marque', models.CharField(max_length=100, verbose_name='Marque')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Immatriculation')),
                ('modele', models.CharField(blank=True, max_length=100, verbose_name='Modèle')),
                ('production_date', models.DateField(verbose_name='Date de production')),
                ('client', models.ForeignKey(help_text='Le client propriétaire de ce véhicule', on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='core.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_debut', models.DateTimeField(verbose_name='Date debut du contrat')),
                ('date_fin', models.DateTimeField(verbose_name='Date debut du contrat')),
                ('actual_date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Date debut reel du contrat')),
                ('actual_date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date fin reel du contrat')),
                ('paid', models.BooleanField(default=False, verbose_name='Sousciption payee ?')),
                ('deposit_paid', models.BooleanField(default=False, verbose_name='Avance payee ?')),
                ('pic_before_device', models.FileField(upload_to='subscriptions/before/', verbose_name='Image Avant sousciption')),
                ('pic_after_device', models.FileField(upload_to='subscriptions/after/', verbose_name='Image Apres souscription')),
                ('pic_on_vehicule', models.FileField(upload_to='subscriptions/vehicule/', verbose_name='Image de l"outils sur le vehicule')),
                ('prix', models.FloatField(blank=True, null=True, verbose_name='Cout de la sousciption')),
                ('incidents', models.TextField(blank=True, null=True, verbose_name='Incident a noter ?')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes sur la souscription ?')),
                ('late_days', models.IntegerField(blank=True, default=0, null=True, verbose_name='Nombre de jour en retard')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('devices', models.ManyToManyField(to='core.device')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.vehicule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
